name: huntersmark
author: cfrankovich
main: dev.frankovich.Plugin
version: 0.0.1
api-version: 1.19
description: Bounty hunter plugin.

commands:
  drop:
    description: Test to drop a star
    usage: /drop
    permission: huntersmark.drop
  updatehearts:
    description: Testing command to update hearts
    usage: /updatehearts <name> <hearts>
    permission: huntersmark.updatehearts
